version: 0.0.1-master.{build}

environment:
  matrix:
    - ARCH: "x86_64"

branches:
  only:
    - master

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

artifacts:
  - path: '*.exe'
  - path: '*.lib'
  - path: 'include\*.*'
  - path: 'include\scales\*\**'

install:
  - git submodule update --init --recursive

before_build:
  - premake4.bat vs2012 winsock

platform: x64
configuration:
  - Release

build:
  project: saurus.sln
